version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    env_file:
      - ./.env
    expose:
      - 8000
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media:/app/media
    depends_on:
      - redis
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
  redis:
    image: redis:alpine
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  celery:
    restart: always
    build:
      context: .
    command: celery -A Book_backend worker --beat -l info
    volumes:
      - .:/app
      - media:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=book
      - DB_USER=postgres
      - DB_PASS=123
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_WORK_DIR=/app
    depends_on:
      - db
      - redis
      - web
  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5557:5555"
    depends_on:
      - redis
volumes:
  db-data:
  static_volume:
  media: