version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    expose:
      - 8000
    restart: always
    volumes:
      - .:/app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
    build: .
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  db-data:
  static_volume:
  media_volume: